server:
  port: 8081

ojas.security.jwt.secret: otherpeopledontknowit

spring:
  datasource:
    #url: jdbc:mysql://192.168.7.190:3306/obs?autoReconnect=true&useSSL=false
    #url: jdbc:mysql://192.168.6.186:3306/ojas_obs?autoReconnect=true&useSSL=false
    #username: dbubora
    #password: Ojas-1525
    #driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver

  