server:
    port: 9020
    
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/ojas_obs
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      profiles:
        active:prod