spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#    password: root
#    url: jdbc:mysql://localhost:3306/ojas_obs
#    username: root





    url: jdbc:mysql://192.168.6.186:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8094
