
server:
   port: 8087
   
spring:
 datasource:


    url: jdbc:mysql://192.168.6.186:3306/ojas_obs   
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver 

#server:
#   port: 8015
#   
#spring:
# datasource:
#   url: jdbc:mysql://localhost:3306/employeebu
#   driver-class-name: com.mysql.jdbc.Driver
#   username: root
#   password: root

 

