server:
  port: 8019 
spring:
 datasource:
    url: jdbc:mysql://192.168.7.64:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/ojas_obs
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver