server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.6.186:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
   